### ISSUE TITLE
Ugly page headlines on very long thesis title

### ISSUE THREAD

**Issue by Akeshihiro** [cagix/pandoc-thesis#3]
Hello,

On my writings I realized that the thesis title is added to the page headline on all pages but the first one of a chapter, so the pages 2–n of a chapter. I think in general this is not an issue, but in my case with a very long title this looks kind of ugly, especially when the section headline touches the thin separation line under the page headline.

<img width="960" alt="screen" src="https://user-images.githubusercontent.com/1447023/66750533-fe40c300-ee8c-11e9-97e1-81ac6742e08e.png">

**Comment by cagix** [comment]
ack. sorry for that ... 

- proposal a: use better (i.e. shorter) thesis titles ;)
- proposal b: i probably should introduce a new variable "shorttitle" or "subtitle" and make use of it in the page header (if defined, otherwise fall back to "title" as of now)

@Akeshihiro do you have any preferences regarding the naming of the new variable? "subtitle" already exists and could be re-used to solve the issue. however, this could be surprising to some people?

**Comment by cagix** [comment]
proposal c: increase height of header. but this will probably destroy the well-balanced definitions of the Eisvogel template ...

**Comment by cagix** [comment]
@Akeshihiro Eisvogel uses `header-left` if defined, otherwise `title` ... so i added this variable to the `metadata.yaml`. you can use it to define a shortened title, which fits into a single line ...

feel free to reopen this issue, if this workaround is not sufficient. Eisvogel uses fanyheaders to define custom headers and footers, so maybe i need to look into this package to see if there is any support for multiline headings ....

**Comment by Akeshihiro** [comment]
@cagix For the moment the usage of `header-left`seems to be a usable approach, thank you very much!

**Comment by cagix** [comment]
@Akeshihiro added in 2c6b19f4dd258f63a12fad27251cf9ee76a6eec5 a new variable `headeralternative` to `metadata.yaml`. if set, the Eisvogel page header will be modified to use the chapter (left page) or the section (right page) instead of the title of the thesis ...
